---
title: "Comparison of YNH and ONH on CDTT English Male"
output: html_document
---

## Summary statistics
```{r, echo=FALSE}
data <- read.csv("/Users/huiwen/Documents/Research/Digit Triplets Test/DTT Part 2 Male talker OA/data_2020_04_22_recalculated/CDTT_EnglishMale_OHN_YNH_2020.04.22.csv", header = TRUE)
data$List <- as.factor(data$List)

hist(data[data$Group == "Younger", ]$SRT, 
  xlim=c(-15, -9), ylim=c(0, 10), main = "Younger", xlab = "SRT", breaks=15, col="grey")
summary(data[data$Group == "Younger", ]$SRT)

hist(data[data$Group == "Older", ]$SRT, 
  xlim=c(-15, -9), ylim=c(0, 10), main = "Older", xlab = "SRT", breaks=15, col="grey")
summary(data[data$Group == "Older", ]$SRT)

```

## Group comparison (younger vs. older)
```{r, echo=FALSE}

library(ggplot2)
# Boxplots with scatter
ggplot(data, aes(x = List, y = SRT)) + 
  facet_grid( ~ Group) + 
  geom_boxplot(outlier.shape=NA) + 
  geom_jitter(height = 0, width = 0.1) + 
  coord_cartesian(xlim=c(1, 4), ylim=c(-14, -9)) + 
  xlab('CDTT List') + 
  ylab('SRT (dB)') + 
  theme_bw() + 
  theme(axis.title = element_text(size = 24), axis.text = element_text(size = 20), text = element_text(size = 22)) + 
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0))) + 
  theme(axis.title.x = element_text(margin = margin(t = 5, r = 0, b = 0, l = 0)))

# ANOVA
summary(with(data, aov(SRT ~ Group*List + Error(factor(SubjectID)/List))))

```

Mean of Older Group - Mean of Younger Group
``` {r, echo=FALSE}

mean(data[data$Group == "Older", ]$SRT) - mean(data[data$Group == "Younger", ]$SRT)

```
